name: Build and Lint for Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Run TypeScript build
        run: yarn build

      - name: Lint and check for unused variables
        run: yarn lint

      - name: Run tests
        run: yarn test
